### ISSUE TITLE
Hold or toggle key with gesture

### ISSUE THREAD

**Issue by toxict2** [acidcoke/Grimassist#11]
Is it possible to have a key held down while you make a gesture and released when you stop? or to use a gesture to toggle a key down/up?

**Comment by acidcoke** [comment]
Currently, there are two types of triggers. `hold` is used by default for every action. With this trigger a key is pressed as long as the gesture is being held. The trigger `single` only presses a key once. You can adjust them by opening `keyboard_bindings.json` or `mouse_bindings.json` in a text editor and changing `trigger_type` to `hold` or `single` for the desired gesture. We still need to implement this in the Gui.

A toggle trigger should be fairly easy to implement as well.

**Comment by toxict2** [comment]
very cool thank you, also would it be possible to map head movement to w,a,s,d instead of moving the mouse?

**Comment by acidcoke** [comment]
Remapping the head movement to different actions is definitely a feature that I want to implement, even though it is much more complicated to implement

**Comment by toxict2** [comment]
thanks for the quick reply, If it's of any help to anyone I have found using the free demo of voice attack on steam I can capture key presses from grimassist and turn them into key toggles
